sudo: required

services:
- docker

language: cpp

compiler:
  - gcc

arch:
  packages:
    - asciidoctor
  script:
    - "autoreconf --install"
    - "./configure"
    - "make"
    - "sudo make install"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
