sudo: required


services:
    - docker
script:
    #- chmod a+w .
    - docker build . -t arch
      #- docker run --rm -v $(pwd):/home/docker/build arch -c "sudo chown docker . ; makepkg -s --noconfirm"
      #- docker run -u `stat -c "%u:%g" $(pwd)` --rm -v $(pwd):/home/docker/build arch -c "makepkg -s --noconfirm"
    - docker run  -v $(pwd):/home/docker/build arch -c "cp PKGBUILD /tmp ; cd /tmp; makepkg -s --noconfirm; sudo mv *.tar.xz /home/docker/build"
