sudo: required


services:
    - docker

arch:
    mount:
        - ~/.pkg-cache:/var/cache/pacman/pkg
    script:
        - "gem install asciidoctor"
        - "autoreconf --install"
        - "./configure"
        - "make"
        - "sudo make install"

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
