sudo: required

services:
    - docker

arch:
    packages:
        - "asciidoctor"
    mount:
        - ~/.pkg-cache:/var/cache/pacman/pkg
    script:
        - "sudo pacman -Syu --noconfirm asciidoctor"
        - "autoreconf --install"
        - "./configure"
        - "make"
        - "sudo make install"

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
