sudo: required
services:
    - docker
script:
    - docker build . -t arch
    - docker run  -v $(pwd):/home/docker/build arch -c "cp PKGBUILD /tmp ;
      cd /tmp;
      makepkg -s --noconfirm;
      sudo mv *.tar.xz /home/docker/build"
deploy:
    provider: releases
    api_key:
        secure: "fFHOx3e/HrpnXj9dTiofdK2HEs171sgsJUGzjDsrE60I+W6Y3/coLbO9jhcRLOsuWB62/4liDTuod7toigAJPqYxQsZAs6Esbtxlk+AHR/wwU4y8CK83V2qfOqRhhqFow5DaJpMHZLvxICquNRHescTwl66IQiQ7ZVBnRFKEf5Ds7re8XFNeDqicKPTxr8IC83nz3/Lm5kii+AaVLNw8ynaCyvLlDDPZD0h4BrHwaxS1Wgh66SWi5x5948TWSdV5wFWa3Bp7BZdh38Tq3IQM/2REyyBOUR+wJIuWoTi+JNrkn4kt9U09tQngfnQzEsMXtkB8kK3rQoVh7Wr9/mLZ94VpHbDzJwtXLWlt2J+E8iQtxGs77UcTwq2jQhtsNCtH9ANipBXaibsewdxL5sT8dBaFwFnUY/mIhFOP4qRLyV1Zo6+VRBVQXwxt67/QvxJQZm4pgKIUNMq30iVLzrScj12UfxxEiUqUbe/O2rdQI0mGnYlsVPU+npl0Hhe9sqEWb1Kg4hyGnI7QDC67q0T9gvqGpQlEOgBAQeBtUCM1i1kGLLayy7zFNzmHHeOrsYHvvZYKWnsMjFmCTYgAnZYk9svIWFysDDG9bAWwT96PTd9Q1Gm28PUMjrXDTb5asYK4tgzVnXjvHoUj/BRC23qRgK9XQuLYk/as5yx90x6FdEE="
    file: "*.tar.xz"
    skip_cleanup: true
    on:
        repo: otreblan/hello
        tags: true
