name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: deps
      run: sudo apt install asciidoctor g++-10

    - name: configure
      run: CXXFLAGS="-O2 -pipe -fno-plt -Wall -Wextra" cmake
        -DCMAKE_CXX_COMPILER=g++-10
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=/usr
        -B build

    - name: build
      run: |
          export MAKEFLAGS=-j$(nproc)
          cmake --build build
          cmake --build build --target doc

    - name: deb
      run: cmake --build build --target package

    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu_package
        path: build/*.deb

  arch-linux:
    runs-on: ubuntu-latest
    container: oblique/archlinux-yay

    steps:
    - name: Get last tag
      id: tag
      env:
        REPO: https://github.com/${{ github.repository }}
      run: |
          set -o pipefail
          echo ::set-output name=LAST_TAG::$(git ls-remote --tags $REPO | sed "s#.*refs/tags/\(.*\)#\1#" | awk -F^ '{print $1}' | sort -V | tail -n1)

    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.tag.outputs.LAST_TAG }}

    - name: Checkout repo head
      env:
        REF: ${{ github.ref }}
      run: |
          git fetch origin ${REF#refs/heads/}
          git checkout FETCH_HEAD
          git log --decorate=on

    - name: Zstd
      run: sed -i 's/tar\.xz/tar.zst/' /etc/makepkg.conf

    - name: Syu
      run: sudo -u aur yay -Syu --noconfirm

    - name: chown
      run: chown --recursive aur pkg/arch

    - name: makepkg
      working-directory: ./pkg/arch
      run: |
          export MAKEFLAGS=-j$(nproc)
          sudo -Eu aur makepkg -s --noconfirm

    - uses: actions/upload-artifact@v2
      with:
        name: arch_package
        path: pkg/arch/*.pkg.tar.*
