name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: deps
      run: sudo apt install asciidoctor

    - name: configure
      run: CXXFLAGS="-O2 -pipe -fno-plt" cmake
        -DCMAKE_CXX_COMPILER=g++-9
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=/usr
        -B build

    - name: build
      run: |
          export MAKEFLAGS=-j$(nproc)
          cmake --build build
          cmake --build build --target doc

    - name: deb
      run: cmake --build build --target package

    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu_package
        path: build/*.deb

  arch-linux:
    runs-on: ubuntu-latest
    container: oblique/archlinux-yay

    steps:
    - uses: actions/checkout@v2

    - name: Syu
      run: sudo -u aur yay -Syu --noconfirm

    - name: Zstd
      run: sed -i 's/tar\.xz/tar.zst/' /etc/makepkg.conf

    - name: chown
      run: chown aur pkg/arch

    - name: makepkg
      working-directory: ./pkg/arch
      run: |
          export MAKEFLAGS=-j$(nproc)
          sudo -Eu aur makepkg -s --noconfirm

    - uses: actions/upload-artifact@v2
      with:
        name: arch_package
        path: pkg/arch/*.pkg.tar.*
